---
# Source: helm-bootstrap-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-admin
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
---
# Source: helm-bootstrap-external-secrets/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-admin
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "delete", "list", "watch"]
---
# Source: helm-bootstrap-external-secrets/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-admin
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: vault-admin
roleRef:
  kind: Role
  name: vault-admin
  apiGroup: rbac.authorization.k8s.io
