---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
  namespace: ollama
  labels:
    app: browserless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless
  template:
    metadata:
      labels:
        app: browserless
    spec:
      containers:
        - name: browserless
          image: ghcr.io/browserless/chromium:latest
          env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: browserless-proxy-external-secret
                key: BROWSERLESS_TOKEN
          - name: CONCURRENT
            value: "5"
          - name: TIMEOUT
            value: "60000"
      imagePullSecrets:
        - name: regcred-external-secret
---
apiVersion: v1
kind: Service
metadata:
  name: browserless
  namespace: ollama
spec:
  selector:
    app: browserless
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless-proxy
  namespace: ollama
  labels:
    app: browserless-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless-proxy
  template:
    metadata:
      labels:
        app: browserless-proxy
    spec:
      containers:
        - name: browserless-proxy
          image: ocr.jcan.dev/library/browserles-proxy:0.1.0
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TROPIC_API_URL
              value: "https://api.tropic.bot/api"
            - name: TROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ollama-proxy-external-secret
                  key: TROPIC_API_KEY
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: browserless-proxy-external-secret
                  key: BROWSERLESS_TOKEN
            - name: SERVICE_NAME
              value: "browserless-proxy"
            - name: BROWSERLESS_SERVICE
              value: "browserless"
            - name: BROWSERLESS_PORT
              value: "3000"
      imagePullSecrets:
        - name: regcred-external-secret