---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: browserless-proxy-external-secret
  namespace: ollama
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: browserless-proxy-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: BROWSERLESS_TOKEN
      remoteRef:
        key: TROPIC.BROWSERLESS_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ollama-proxy-external-secret
  namespace: ollama
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: ollama-proxy-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: TROPIC_API_KEY
      remoteRef:
        key: TROPIC.API_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regcred-external-secret
  namespace: ollama
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: regcred-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        .dockerconfigjson: '{{ .base64Regcred | toString }}'
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: base64Regcred
      remoteRef:
        key: HARBOR.REGCRED