apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  argocd.argoproj.io/instance: argo-cd

resources:
- namespace.yaml

helmCharts:
- name: argo-cd
  namespace: argo-cd
  releaseName: argo-cd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  version: 8.1.1