# -- Provide a name in place of `argocd`
nameOverride: "argo-cd"

global:
  image:
    tag: v2.11.3  # Replace with desired Argo CD version

controller:
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

dex:
  enabled: true
  replicas: 2
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Use regular Redis (non-HA)
redis:
  enabled: true
  replicas: 2  # Horizontal scaling for availability, not replication
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

redis-ha:
  enabled: false

server:
  replicas: 2
  autoscaling:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    ports:
      http: 80
      https: 443

repoServer:
  replicas: 2
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

applicationSet:
  replicaCount: 2
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

notifications:
  enabled: true
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

configs:
  params:
    server.insecure: "true"
    controller.shard.count: "1"
    applicationsetcontroller.enable.leader.election: "true"

  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-helm"
    exec.enabled: "true"

  rbac:
    policy.default: role:readonly