---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: cloudflare-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: CLOUDFLARE.API_KEY
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: CLOUDFLARE.API_TOKEN
    - secretKey: CLOUDFLARE_EMAIL
      remoteRef:
        key: CLOUDFLARE.EMAIL
