---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-external-secret
  namespace: secrets-integrator
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/bitwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: maccount-user
      secretKey: maccount-user
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/bitwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: maccount-token
      secretKey: maccount-token
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: bitwarden-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsstore
  namespace: secrets-integrator
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            name: bitwarden-external-secret
            namespace: secrets-integrator
            key: maccount-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: "201646e4-8da7-4b97-9e94-b479007a4429"
      projectID: "757ba20e-062e-4e41-8302-b4d40009dd15"
      caProvider:
        type: Secret
        name: bitwarden-ca-certs
        namespace: external-secrets
        key: ca.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-bitwarden-external-secret
  namespace: secrets-integrator
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: test-bitwarden-external-secret
    creationPolicy: Owner
  data:
    - secretKey: FOO
      remoteRef:
        key: foo