---
# Source: secrets-integrator/templates/external-secrets/cluster-secretstore.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  namespace: secrets-integrator
  annotations: 
    vault.hashicorp.com/role: bao-admin
spec:
  provider: 
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: bao-admin
          namespace: secrets-integrator
      path: kv
      server: http://openbao.openbao.svc.cluster.local:8200
      version: v2
