---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sd-comfyui-models-pv
  labels:
    app.kubernetes.io/instance: sd-comfyui
    app.kubernetes.io/component: sd-comfyui
    app.kubernetes.io/part-of: workloads-ai
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /mnt/disk1/sd-comfyui/output
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - "turing"
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: local-storage