apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: gpu-operator
  namespace: nvidia-operator
  releaseName: nvidia-operator
  repo: https://helm.ngc.nvidia.com/nvidia
  valuesFile: values.gpu-operator.yaml
  version: v26.3.0
  includeCRDs: true
- name: dcgm-exporter
  namespace: nvidia-operator
  releaseName: dcgm-exporter
  repo: https://nvidia.github.io/dcgm-exporter/helm-charts
  valuesFile: values.dcgm-exporter.yaml
  version: 4.8.1