affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "nvidia.com/gpu.present"
              operator: Exists

runtimeClassName: "nvidia"

securityContext:
  capabilities:
    add:
      - SYS_ADMIN