apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-external-secret
  namespace: external-dns
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: platform/security/dnsfix
      metadataPolicy: None
      property: CLOUDFLARE_API_TOKEN
    secretKey: CF_API_TOKEN
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: platform/security/dnsfix
      metadataPolicy: None
      property: CLOUDFLARE_API_KEY
    secretKey: CF_API_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: platform/security/dnsfix
      metadataPolicy: None
      property: CLOUDFLARE_EMAIL
    secretKey: CF_API_EMAIL
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: external-dns-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd