apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml

helmCharts:
- name: kube-prometheus-stack
  namespace: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.yaml
  version: 75.11.0
  includeCRDs: true