# metallb-values.yaml

# Enable MetalLB controller and speaker
controller:
  enabled: true

speaker:
  enabled: true

# Ensure compatibility with Cilium (which handles routing via eBPF)
# No need to enable kube-proxy mode
crds:
  enabled: true

# To avoid any conflict with Cilium, don't enable bgp if you're not using it.
# Instead, use Layer 2 (ARP) mode for IP advertisement.

# Optional: if you want logs/debugging
logLevel: info
