# TODO: migrate cloudflare credentials path from dnsfix to cloudflare
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: gateway
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/dnsfix
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: CLOUDFLARE_API_KEY
      secretKey: CLOUDFLARE_API_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/dnsfix
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: CLOUDFLARE_API_TOKEN
      secretKey: CLOUDFLARE_API_TOKEN
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/dnsfix
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: CLOUDFLARE_EMAIL
      secretKey: CLOUDFLARE_EMAIL
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: letsencrypt-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
