---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: gateway # Adjust to your target namespace
  annotations:
    # Link this Gateway to Traefik's internal EntryPoints
    gateway.traefik.io/entrypoints: web,websecure
    # This annotation triggers cert-manager to create a Certificate
    cert-manager.io/cluster-issuer: "le-gw-prd"
spec:
  gatewayClassName: traefik # Ensure this matches your Traefik GatewayClass
  listeners:
  - name: https
    protocol: HTTPS
    port: 8443
    hostname: demo.jcan.dev
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret	
        name: contacts-tls-secret # cert-manager populates this secret
  - name: http
    protocol: HTTP
    port: 8000
    allowedRoutes:
      namespaces:
        from: All