{{- $appNamespace := "argo-cd" -}}
{{- $destinationServer := .Values.spec.destination.server -}}
{{- $appProject := .Values.spec.project -}}
{{- $repoURL := .Values.spec.source.repoURL -}}
{{- $targetRevision := .Values.spec.source.targetRevision -}}

{{- range $app, $value := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: {{ $appNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncWave | default "99" | quote }}
  labels:
    app: {{ $app }}
    argocd.argoproj.io/appproject: {{ $appProject }}
    {{ $appProject }}/installType: {{ $value.installType }}
    {{- if $value.extraLabels }}
    {{- toYaml $value.extraLabels | nindent 4 }}
    {{- end }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $value.namespace | default $app }}
    server: {{ $destinationServer }}
  project: {{ $appProject }}
  {{- if eq $value.installType "localKustomize" }}
  sources:
    - repoURL: {{ $repoURL  }}
      targetRevision: {{ $targetRevision }}
      path: "src/projects/configurations/{{ $appProject }}/{{ $app }}"
  {{- else if eq $value.installType "localHelm" }}
  sources:
    - repoURL: {{ $repoURL  }}
      targetRevision: {{ $targetRevision }}
      path: "src/projects/configurations/{{ $appProject }}/{{ $app }}"
  {{- else }}
  sources:
    - repoURL: {{ $value.repoURL }}
      targetRevision: {{ $value.targetRevision }}
      helm:
        valueFiles:
          - $values/src/projects/configurations/{{ $appProject }}/{{ $app }}/values.yaml
  {{- if eq $value.installType "helm" }}
      chart: {{ $value.chartName }}
  {{- else if eq $value.installType "oci" }}
      chart: {{ $value.chartName }}
      path: {{ $value.path }}
  {{- else }}
      path: {{ $value.path }}
  {{- end }}
    - repoURL: {{ $repoURL }}
      targetRevision: {{ $targetRevision }}
      ref: values
  {{- end }}
  syncPolicy:
    {{- if $value.automated }}
    automated:
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
    {{- range $option := $value.extraSyncOptions | default dict }}
      - {{ toYaml $option }}
    {{- end }}
  {{- if $value.ignoreDifferences }}
  ignoreDifferences: {{ toYaml $value.ignoreDifferences | nindent 4 }}
  {{- end }}
{{- end }}
