apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: strimzi-kafka-operator
  namespace: kafka-operator
  releaseName: kafka
  repo: https://strimzi.io/charts/
  valuesFile: values.yaml
  version: 0.47.0

resources:
- namespace.yaml