---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant-external-secret
  namespace: qdrant
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: qdrant-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: QDRANT_SERVICE_API_KEY
      remoteRef:
        key: QDRANT.SERVICE_API_KEY
