apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant-external-secret
  namespace: qdrant
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: platform/storage/qdrant
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: QDRANT_SERVICE_API_KEY
      secretKey: QDRANT_SERVICE_API_KEY
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: qdrant-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd