---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-admin.service-account-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: argo-workflows-admin
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-default.service-account-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token