{{- range $app, $value := .Values.externalSecret.clusterSecretStore }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ $app }}
  annotations: {{ toYaml $value.annotations | nindent 4}}
spec:
  provider: {{ toYaml $value.provider | nindent 4 }}
{{- end }}