apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-external-secret
  namespace: jupyterhub
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/tools/jupyterhub
        metadataPolicy: None
        property: GITLAB_APPLICATION_ID
      secretKey: GITLAB_APPLICATION_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/tools/jupyterhub
        metadataPolicy: None
        property: GITLAB_CLIENT_SECRET
      secretKey: GITLAB_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/tools/jupyterhub
        metadataPolicy: None
        property: GITLAB_CALLBACK_URL
      secretKey: GITLAB_CALLBACK_URL
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: JUPYTERHUB_CLIENT_ID
      secretKey: JUPYTERHUB_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: JUPYTERHUB_CLIENT_SECRET
      secretKey: JUPYTERHUB_CLIENT_SECRET
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: jupyterhub-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd