---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-external-secret
  namespace: jupyterhub
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: jupyterhub-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: GITLAB_APPLICATION_ID
      remoteRef:
        key: JUPYTERHUB.GITLAB_APPLICATION_ID
    - secretKey: GITLAB_CLIENT_SECRET
      remoteRef:
        key: JUPYTERHUB.GITLAB_CLIENT_SECRET
    - secretKey: GITLAB_CALLBACK_URL
      remoteRef:
        key: JUPYTERHUB.GITLAB_CALLBACK_URL
    - secretKey: JUPYTERHUB_CLIENT_ID
      remoteRef:
        key: JUPYTERHUB.AUTHENTIK_CLIENT_ID
    - secretKey: JUPYTERHUB_CLIENT_SECRET
      remoteRef:
        key: JUPYTERHUB.AUTHENTIK_CLIENT_SECRET
