---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: kube-prometheus-stack
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: grafana-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: GF_AUTH_GITLAB_CLIENT_ID
      remoteRef:
        key: GRAFANA.GITLAB_APPLICATION_ID
    - secretKey: GF_AUTH_GITLAB_CLIENT_SECRET
      remoteRef:
        key: GRAFANA.GITLAB_CLIENT_SECRET

    - secretKey: GF_AUTH_AUTHENTIK_CLIENT_ID
      remoteRef:
        key: GRAFANA.AUTHENTIK_CLIENT_ID
    - secretKey: GF_AUTH_AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: GRAFANA.AUTHENTIK_CLIENT_SECRET