{{- range $app, $value := .Values.externalSecret.externalSecrets }}
{{- range $namespace := $value.namespaces }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $value.name | quote }}
  namespace: {{ $namespace | quote }}
  {{- if $value.labels }}
  labels:
    {{- toYaml $value.labels | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: "15s"
  secretStoreRef: {{ toYaml $value.secretStoreRef | nindent 4 }}
  target:
    name: {{ $value.name }}
    {{- if $value.template }}
    template:
    {{- toYaml $value.template | nindent 6 }}
    {{- end }}
  data:
    {{- toYaml $value.data | nindent 4 }}
{{- end }}
{{- end }}