apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pft-external-secret-regcred
  namespace: pft
spec:
  data:
    - secretKey: base64Regcred
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: workloads/work/pft
        metadataPolicy: None
        property: regcred
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pft-external-secret-regcred
    template:
      data:
        .dockerconfigjson: '{{ .base64Regcred | toString }}'
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson