apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pft-external-secret
  namespace: argo-cd
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/work/pft
        metadataPolicy: None
        property: username
      secretKey: username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/work/pft
        metadataPolicy: None
        property: access-token
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/work/pft
        metadataPolicy: None
        property: url
      secretKey: url
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/work/pft
        metadataPolicy: None
        property: type
      secretKey: type
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/work/pft
        metadataPolicy: None
        property: name
      secretKey: name
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/work/pft
        metadataPolicy: None
        property: project
      secretKey: project
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pft-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: repository