---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-external-secret
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: litellm-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: masterkey
      remoteRef:
        key: LITELLM.MASTER_KEY
    - secretKey: password
      remoteRef:
        key: LITELLM.DB_PASSWORD
    - secretKey: username
      remoteRef:
        key: LITELLM.DB_USERNAME
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        key: LITELLM.SALT_KEY
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: LITELLM.REDIS_PASSWORD