apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- external-secret.yaml
- db-postgres.yaml

helmCharts:
- name: litellm
  releaseName: litellm
  namespace: litellm
  repo: oci://ghcr.io/berriai/litellm/chart/litellm
  valuesFile: values.yaml
  version: 1.104.0
  includeCRDs: true