fullnameOverride: "litellm"
liteadmin:
  backendUrl: "http://litellm-gateway:4000"

masterKey:
  secretName: litellm-external-secret
  secretKey: masterkey

database:
  writer:
    host: "litellm-postgres-rw:5432/litellm"
    port: 5432
    dbname: litellm
    passwordSecret:
      name: litellm-external-secret
      usernameKey: username
      passwordKey: password

redis:
  host: "litellm-redis"
  port: 6379
  passwordSecret:
    name: litellm-external-secret
    passwordKey: REDIS_PASSWORD

# one host fronting gateway, backend, and ui
ingress:
  enabled: true
  className: "cilium"
  annotations:
    cert-manager.io/cluster-issuer: le-ing-prd
    ingress.cilium.io/loadbalancer-mode: shared
    ingress.cilium.io/websocket: "enabled"
  host: "llm.jcan.dev"