apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/rancher/system-upgrade-controller
resources:
- namespace.yaml
- https://raw.githubusercontent.com/rancher/system-upgrade-controller/refs/tags/v0.15.3/manifests/clusterrole.yaml
- https://raw.githubusercontent.com/rancher/system-upgrade-controller/refs/tags/v0.15.3/clusterrolebinding.yaml
- https://raw.githubusercontent.com/rancher/system-upgrade-controller/refs/tags/v0.15.3/system-upgrade-controller.yaml
