apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich

spec:
  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vector"   # required if using pgvector

  storage:
    size: 20Gi
    storageClass: longhorn

  managed:
    roles:
      - name: immichuser
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1

        passwordSecret:
          name: immich-external-secret

  bootstrap:
    initdb:
      database: immichdb
      owner: immichuser

      # Install required extensions ONCE at cluster init
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;