apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- external-secret.yaml
- configs
- immich-redis
- db-postgres.yaml
# - immich-database
# - immich-machine-learning
# - immich-server
# - ingress.yaml

helmCharts:
- name: immich
  namespace: immich
  repo: oci://ghcr.io/immich-app/immich-charts/immich
  valuesFile: values.yaml
  version: 0.13.1
  includeCRDs: true