grafana:
  enabled: true

  envFromSecret: gitlab-grafana-oauth

  adminPassword: null
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'default'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/standard

  dashboards:
    default:
      nvidia-dcgm-exporter:
        gnetId: 12239
        revision: 2
        datasource:
          - name: Prometheus
            value: Prometheus

  grafana.ini:
    auth:
      # remove the login form from the sign-in page 
      disable_login_form: false

      basic:
        # disable HTTP Basic Authentication
        enabled: true

      gitlab:
        enabled: true
        # # go directly to SSO! (hint: `/login?disableAutoLogin`)
        # auto_login: false
        # allow_sign_up: true
        allowed_groups:
        - Kube-Mind
        allowed_domains:
        - grafana.jcan.dev
        - jcan.dev
        # redirect_uri: https://grafana.jcan.dev/api/auth/callback/gitlab
        role_attribute_path: "contains(groups[*], 'Kube-Mind') && 'Editor' || 'Viewer'"
        role_attribute_strict: false
        scopes:
        - read_user
        - read_api
        - read_repository
        - openid
        - profile
        - email
        - read_group
      
      oauth_generic:
        enabled: true
        # go directly to SSO! 🎉 (hint: `/login?disableAutoLogin`)
        auto_login: false

        # there's about to be a 👻 JSON query, by setting this to strict,
        # Grafana will reject logins if the expression errors
        # (fail closed)
        role_attribute_strict: true

        # LDAP group -> Grafana role mapping:
        # `grafana_admin` -> Grafana **Server** Admin
        # `grafana_editor` -> Grafana Editor
        # * -> Grafana Viewer
        # role_attribute_path: contains(groups[*], 'grafana_admin') && 'GrafanaAdmin' || contains(groups[*], 'grafana_editor') && 'Editor' || 'Viewer'

        # required for the above query ⬆️ to be able to map to Grafana **Server** Admin
        allow_assign_grafana_admin: true
        auth_url: https://gitlab.com/oauth/authorize
        token_url: https://gitlab.com/oauth/token
        api_url: https://gitlab.com/api/v4

    server:
      domain: grafana.jcan.dev
      external_url: https://grafana.jcan.dev

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prd
    hosts:
    - grafana.jcan.dev
    tls:
    - secretName: "grafana-tls-key"
      hosts:
      - grafana.jcan.dev

prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false

prometheus:
  annotations:
    argocd.argoproj.io/skip-health-check: 'true'
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
    - job_name: gpu-metrics
      scrape_interval: 1s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - nvidia-operator
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node

prometheus-node-exporter:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/etcd
      operator: Exists
      effect: NoExecute