apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-external-secret
  namespace: open-webui
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ai/open-webui
        metadataPolicy: None
        property: GITLAB_APPLICATION_ID
      secretKey: OAUTH_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ai/open-webui
        metadataPolicy: None
        property: GITLAB_CLIENT_SECRET
      secretKey: OAUTH_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ai/open-webui
        metadataPolicy: None
        property: GOOGLE_CLIENT_ID
      secretKey: GOOGLE_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ai/open-webui
        metadataPolicy: None
        property: GOOGLE_CLIENT_SECRET
      secretKey: GOOGLE_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ai/open-webui
        metadataPolicy: None
        property: PIPELINES_API_KEY
      secretKey: PIPELINES_API_KEY
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: open-webui-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd