---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-external-secret
  namespace: open-webui
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: open-webui-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: OPENWEBUI.AUTHENTIK_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: OPENWEBUI.AUTHENTIK_CLIENT_SECRET

    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: OPENWEBUI.GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: OPENWEBUI.GOOGLE_CLIENT_SECRET
    
    - secretKey: PIPELINES_API_KEY
      remoteRef:
        key: OPENWEBUI.PIPELINES_API_KEY
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: OPENWEBUI.OPENAI_API_KEY
    - secretKey: OPENWEBUI_SECRET_KEY
      remoteRef:
        key: OPENWEBUI.SECRET_KEY
    - secretKey: username
      remoteRef:
        key: OPENWEBUI.DB_USER
    - secretKey: password
      remoteRef:
        key: OPENWEBUI.DB_PASSWORD
    - secretKey: QDRANT_SERVICE_API_KEY
      remoteRef:
        key: QDRANT.SERVICE_API_KEY