---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: open-webui
  namespace: open-webui
spec:
  headers:
    customRequestHeaders:
      Connection: "Upgrade"
      Upgrade: "websocket"