apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dependencies/middleware.yaml
- dependencies/storage.yaml
- application-set.yaml

generatorOptions:
  disableNameSuffixHash: true