apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-external-secret
  namespace: kube-prometheus-stack
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/observability/alertmanager
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: ALERT_MANAGER_WEBHOOK
      secretKey: ALERT_MANAGER_WEBHOOK
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: alertmanager-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd