apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argo-cd
  name: infrastructure
  labels:
    app.kubernetes.io/instance: infrastructure
    app.kubernetes.io/part-of: main
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/tracking-id: default:argoproj.io/Application:argo-cd/infrastructure
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - name: infra-core
          group: infrastructure
          component: core
        - name: infra-network
          group: infrastructure
          component: network
        - name: infra-storage
          group: infrastructure
          component: storage
        - name: infra-observability
          group: infrastructure
          component: observability
        - name: infra-security
          group: infrastructure
          component: security
  template:
    metadata:
      name: '{{ .name }}'
      namespace: '{{ .name }}'
      annotations:
        argocd.argoproj.io/tracking-id: infrastructure:argoproj.io/Application:argo-cd/{{ .name }}
      labels:
        app.kubernetes.io/component: '{{ .component }}'
        app.kubernetes.io/part-of: '{{ .group }}'
    spec:
      project: infrastructure
      source:
        repoURL: https://gitlab.com/Kube-Mind/fleet-infra.git
        targetRevision: main
        path: 'k8s/{{ .group }}/{{ .component }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: '{{ .group }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true