apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: hami
  namespace: hami
  releaseName: hami
  repo: https://project-hami.github.io/HAMi/
  valuesFile: values.yaml
  version: 2.10.0
  includeCRDs: true

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: hami-device-plugin
      namespace: hami
    patch: |-
      - op: add
        path: /spec/template/spec/runtimeClassName
        value: nvidia