apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-external-secret
  namespace: external-secrets
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/bitwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: maccount-user
      secretKey: maccount-user
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/bitwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: maccount-token
      secretKey: maccount-token
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: bitwarden-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-ca
  namespace: external-secrets
spec:
  isCA: true
  commonName: bitwarden-sdk-ca
  secretName: bitwarden-ca-certs
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: internal-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs

  issuerRef:
    name: bitwarden-ca-issuer
    kind: Issuer
    group: cert-manager.io

  dnsNames:
    - bitwarden-sdk-server
    - bitwarden-sdk-server.external-secrets
    - bitwarden-sdk-server.external-secrets.svc
    - bitwarden-sdk-server.external-secrets.svc.cluster.local

  privateKey:
    algorithm: ECDSA
    size: 256

  usages:
    - digital signature
    - key encipherment
    - server auth