apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: harbor-timeouts
  namespace: harbor
spec:
  services:
  - name: harbor-core
    namespace: harbor
  resources:
  - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: harbor-routes
    virtual_hosts:
    - name: harbor
      domains:
        - "ocr.jcan.dev"
      routes:
        - match:
            prefix: "/"
          route:
            cluster: harbor
            timeout: 0s