apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-workflows
spec:
  # Native NATS-based EventBus
  nats:
    native:
      replicas: 1
      # Optional: configure resources
      resources:
        requests:
          memory: 64Mi
          cpu: 100m
        limits:
          memory: 128Mi
          cpu: 200m