---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ollama-proxy-external-secret
  namespace: ollama
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ai/ollama-proxy
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: TROPIC_API_KEY
      secretKey: TROPIC_API_KEY
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ollama-proxy-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regcred-external-secret
  namespace: ollama
spec:
  data:
    - secretKey: base64Regcred
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: platform/storage/harbor
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: regcred
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: regcred-external-secret
    template:
      data:
        .dockerconfigjson: '{{ .base64Regcred | toString }}'
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson