---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: contacts-gateway
  namespace: contacts # Adjust to your target namespace
  annotations:
    # Link this Gateway to Traefik's internal EntryPoints
    gateway.traefik.io/entrypoints: web,websecure
    # This annotation triggers cert-manager to create a Certificate
    cert-manager.io/cluster-issuer: "letsencrypt-prd"
spec:
  gatewayClassName: traefik # Ensure this matches your Traefik GatewayClass
  listeners:
  - name: https
    protocol: HTTPS
    port: 8443
    hostname: demo.jcan.dev
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret	
        name: contacts-tls-secret # cert-manager populates this secret
  - name: http
    protocol: HTTP
    port: 8000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: contacts-route
  namespace: contacts
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    kind: Gateway	
    name: contacts-gateway
    namespace: contacts
    sectionName: https
  hostnames:
  - demo.jcan.dev
  rules:
  - backendRefs:
    - group: ''	
      kind: Service	
      name: client # Your existing K8s Service
      port: 3000
      weight: 1	
    matches:	
      - path:
          type: PathPrefix	
          value: /