
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dnsfix-external-secret
  namespace: dnsfix
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: dnsfix-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - remoteRef:
        key: CLOUDFLARE.API_KEY
      secretKey: CLOUDFLARE_API_KEY
    - remoteRef:
        key: CLOUDFLARE.API_TOKEN
      secretKey: CLOUDFLARE_API_TOKEN
    - remoteRef:
        key: CLOUDFLARE.EMAIL
      secretKey: CLOUDFLARE_EMAIL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regcred-external-secret
  namespace: dnsfix
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: regcred-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - remoteRef:
        key: HARBOR.REGCRED
      secretKey: base64Regcred