apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dnsfix-external-secret
  namespace: dnsfix
spec:
  data:
    - secretKey: base64Regcred
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: platform/storage/dnsfix
        metadataPolicy: None
        property: regcred
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: dnsfix-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd