---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-external-secret
  namespace: rabbitmq
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: rabbitmq-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: RABBITMQ.PASSWORD
    - secretKey: rabbitmq-erlang-cookie
      remoteRef:
        key: RABBITMQ.ERLANG_COOKIE
