apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-external-secret
  namespace: external-dns
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/messaging/rabbitmq
        metadataPolicy: None
        property: rabbitmq-password
      secretKey: rabbitmq-password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/messaging/rabbitmq
        metadataPolicy: None
        property: rabbitmq-erlang-cookie
      secretKey: rabbitmq-erlang-cookie
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: rabbitmq-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd