apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neuvector-external-secret
  namespace: neuvector
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/neuvector
        metadataPolicy: None
        property: NEUVECTOR_ADMIN_PASSWORD
      secretKey: NEUVECTOR_ADMIN_PASSWORD
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: neuvector-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd