fullnameOverride: ""
nameOverride:

enabled: true

debug:
  enabled: true

hub:
  config:
    Authenticator:
      admin_users:
      - jesmigel
    JupyterHub:
      allow_named_servers: true
      admin_users:
        - jesmigel
        - admin
      authenticator_class: gitlab

    GitLabOAuthenticator:
      # the following are obtained from OS env vars
      # - https://github.com/jupyterhub/oauthenticator/blob/main/oauthenticator/gitlab.py
      # client_id: env:OAUTH_CLIENT_ID
      # client_secret: env:OAUTH_CLIENT_SECRET
      # oauth_callback_url: env:OAUTH_CALLBACK_URL
      gitlab_url: https://gitlab.com
      scope:
        - "read_api"
        - "read_user"
        - "openid"
        - "profile"
        - "email"
      username_key: username
      gitlab_group_whitelist: ["Kube-Mind"]
      gitlab_project_id_whitelist: []

  extraEnv:
    GITLAB_HOST: https://gitlab.com
    OAUTH_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_APPLICATION_ID
    OAUTH_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_CLIENT_SECRET
    OAUTH_CALLBACK_URL:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_CALLBACK_URL

  service:
    type: ClusterIP

singleuser:
  startTimeout: 3600
  memory:
    guarantee: 1G
    limit: 2G
  cpu:
    guarantee: 2
    limit: 4
  storage:
    type: none
    # dynamic:
    #   storageClass: longhorn

scheduling:
  userScheduler:
    enabled: false
    revisionHistoryLimit:
    replicas: 2
    logLevel: 5

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - jhub.jcan.dev

  tls:
    - hosts:
        - jhub.jcan.dev
      secretName: jupyterhub-tls

prePuller:
  hook:
    enabled: true
  continuous:
    enabled: true
