fullnameOverride: ""
nameOverride:

enabled: true

debug:
  enabled: true

hub:
  config:
    JupyterHub:
      allow_named_servers: true
      admin_users:
        - admin
      authenticator_class: gitlab

    GitLabOAuthenticator:
      client_id: env:OAUTH_CLIENT_ID
      client_secret: env:OAUTH_CLIENT_SECRET
      oauth_callback_url: env:OAUTH_CALLBACK_URL
      gitlab_url: https://gitlab.com
      scope:
        - read_user
      allowed_users:
        - admin
      username_key: username

  extraEnv:
    OAUTH_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_APPLICATION_ID
    OAUTH_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_CLIENT_SECRET
    OAUTH_CALLBACK_URL:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_CALLBACK_URL

  extraConfig:
    remove_insecure_auth: |
      # Remove insecure DummyAuthenticator settings
      pass

  service:
    type: ClusterIP

singleuser:
  startTimeout: 3600
  memory:
    guarantee: 1G
    limit: 2G
  cpu:
    guarantee: 2
    limit: 4
  storage:
    type: dynamic
    dynamic:
      storageClass: longhorn

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: jhub.jcan.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - jhub.jcan.dev
      secretName: jupyterhub-tls

prePuller:
  hook:
    enabled: true
  continuous:
    enabled: true
