# fullnameOverride and nameOverride distinguishes blank strings, null values,
# and non-blank strings. For more details, see the configuration reference.
fullnameOverride: ""
nameOverride:

# enabled is ignored by the jupyterhub chart itself, but a chart depending on
# the jupyterhub chart conditionally can make use this config option as the
# condition.
enabled: true

hub:
  config:
    JupyterHub:
      authenticator_class: dummy
      allow_named_servers: true
      admin_users:
        - admin
  extraConfig:
    dummy_auth: |
      c.Authenticator.admin_users = {'admin'}
      c.DummyAuthenticator.password = "admin"
      c.Spawner.start_timeout = 360

  service:
    type: ClusterIP

singleuser:
  defaultUrl: "/lab"
  image:
    name: jupyter/minimal-notebook
    tag: latest
  memory:
    guarantee: 512M
    limit: 1G
  cpu:
    guarantee: 0.5
    limit: 1
  storage:
    type: dynamic
    capacity: 1G
    dynamic:
      storageClass: longhorn

ingress:
  enabled: false

prePuller:
  hook:
    enabled: true
  continuous:
    enabled: true
