fullnameOverride: ""
nameOverride:

enabled: true

debug:
  enabled: true

hub:
  config:
    JupyterHub:
      allow_named_servers: true
      admin_users:
        - admin
      authenticator_class: gitlab

    GitLabOAuthenticator:
      gitlab_url: https://gitlab.com
      enable_auth_state: true
      scope:
        - read_user
      username_key: username

  extraEnv:
    OAUTH_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_APPLICATION_ID
    OAUTH_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_CLIENT_SECRET
    OAUTH_CALLBACK_URL:
      valueFrom:
        secretKeyRef:
          name: jupyterhub-external-secret
          key: GITLAB_CALLBACK_URL


  service:
    type: ClusterIP

singleuser:
  startTimeout: 3600
  memory:
    guarantee: 1G
    limit: 2G
  cpu:
    guarantee: 2
    limit: 4
  storage:
    type: dynamic
    dynamic:
      storageClass: longhorn

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - jhub.jcan.dev

  tls:
    - hosts:
        - jhub.jcan.dev
      secretName: jupyterhub-tls

prePuller:
  hook:
    enabled: true
  continuous:
    enabled: true
