apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cilium
  namespace: cilium
  releaseName: cilium
  repo: https://helm.cilium.io/
  valuesFile: values.yaml
  version: 1.17.5

resources:
- namespace.yaml