apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-tutorial-external-secret
  namespace: django-tutorial
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/demo/django-tutorial
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: POSTGRES_PASSWORD
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/demo/django-tutorial
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: POSTGRES_USER
      secretKey: POSTGRES_USER
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/demo/django-tutorial
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: DJANGO_ADMIN_PASS
      secretKey: DJANGO_ADMIN_PASS
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/demo/django-tutorial
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: DJANGO_ADMIN_USER
      secretKey: DJANGO_ADMIN_USER
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/demo/django-tutorial
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: SECRET_KEY
      secretKey: SECRET_KEY
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: open-webui-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd