---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-tutorial-external-secret
  namespace: django-tutorial
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: django-tutorial-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: DEMO.POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: DEMO.POSTGRES_USER
    - secretKey: DJANGO_ADMIN_PASS
      remoteRef:
        key: DEMO.DJANGO_ADMIN_PASS
    - secretKey: DJANGO_ADMIN_USER
      remoteRef:
        key: DEMO.DJANGO_ADMIN_USER
    - secretKey: SECRET_KEY
      remoteRef:
        key: DEMO.SECRET_KEY