apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-external-secret
  namespace: harbor
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: platform/storage/harbor
        metadataPolicy: None
        property: SSO_AUTHENTIK_OVERWRITE_JSON
      secretKey: CONFIG_OVERWRITE_JSON
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: harbor-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd