---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-external-secret
  namespace: harbor
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: harbor-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: CONFIG_OVERWRITE_JSON
      remoteRef:
        key: HARBOR.OVERRIDE_CONFIG_AUTHENTIK