.PHONY: cilium-setup cilium-wait cilium-proxy cilium-teardown 
CILIUM_NAMESPACE=kube-system
CILIUM_PATH=./src/platform/network/cilium
CILIUM_VALUES=$(CILIUM_PATH)/values.yaml
cilium-setup:
	$(call kustomize_apply,$(CILIUM_PATH))

cilium-get-resources:
	$(call kustomize_get,$(CILIUM_PATH))

cilium-wait:
	$(call k8s_wait_pods_ready,$(CILIUM_NAMESPACE),io.cilium/app=operator)
	$(call k8s_wait_pods_ready,$(CILIUM_NAMESPACE),app.kubernetes.io/name=cilium-envoy)
	$(call k8s_wait_pods_ready,$(CILIUM_NAMESPACE),app.kubernetes.io/name=cilium)

cilium-teardown:
	$(call kustomize_delete,$(CILIUM_PATH))

cilium-proxy:
	kubectl -n $(CILIUM_NAMESPACE) port-forward svc/hubble-ui 8082:80

.PHONY: cilium-refresh-relay
cilium-refresh-relay:
	# Delete the secrets so they can be regenerated by the operator
	kubectl -n $(CILIUM_NAMESPACE) delete secret hubble-relay-client-certs
	kubectl -n $(CILIUM_NAMESPACE) delete secret hubble-server-certs

	# Restart the relay to force it to pick up new secrets
	kubectl -n $(CILIUM_NAMESPACE) rollout restart deployment hubble-relay
