enabled: true
installCRDs: true

resources:
  # Controller managing certs
  certManager:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  # Webhook server (validates cert-manager CRDs)
  webhook:
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi

  # CA injector (for injecting CA bundles into secrets)
  cainjector:
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi