---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-external-secret
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: authentik-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: AUTHENTIK.SECRET_KEY
    - secretKey: AUTHENTIK_NOTIFICATIONS_SLACK_WEBHOOK
      remoteRef:
        key: AUTHENTIK.NOTIFICATION_SLACK_WEBHOOK
    # USERS
    - remoteRef:
        key: AUTHENTIK.ADMIN_EMAIL
      secretKey: AUTHENTIK_ADMIN_EMAIL
    - remoteRef:
        key: AUTHENTIK.ADMIN_PASSWORD
      secretKey: AUTHENTIK_ADMIN_PASSWORD
    - remoteRef:
        key: AUTHENTIK.BACKUP_ADMIN_EMAIL
      secretKey: AUTHENTIK_BACKUP_ADMIN_EMAIL
    - remoteRef:
        key: AUTHENTIK.BACKUP_ADMIN_PASSWORD
      secretKey: AUTHENTIK_BACKUP_ADMIN_PASSWORD
    # APPLICATIONS
    - remoteRef:
        key: ARGOCD.AUTHENTIK_CLIENT_ID
      secretKey: ARGOCD_CLIENT_ID
    - remoteRef:
        key: ARGOCD.AUTHENTIK_CLIENT_SECRET
      secretKey: ARGOCD_CLIENT_SECRET
    - remoteRef:
        key: ARGOWF.AUTHENTIK_CLIENT_ID
      secretKey: ARGOWF_CLIENT_ID
    - remoteRef:
        key: ARGOWF.AUTHENTIK_CLIENT_SECRET
      secretKey: ARGOWF_CLIENT_SECRET
    - remoteRef:
        key: GRAFANA.AUTHENTIK_CLIENT_ID
      secretKey: GRAFANA_CLIENT_ID
    - remoteRef:
        key: GRAFANA.AUTHENTIK_CLIENT_SECRET
      secretKey: GRAFANA_CLIENT_SECRET
    - remoteRef:
        key: HARBOR.AUTHENTIK_CLIENT_ID
      secretKey: HARBOR_CLIENT_ID
    - remoteRef:
        key: HARBOR.AUTHENTIK_CLIENT_SECRET
      secretKey: HARBOR_CLIENT_SECRET
    - remoteRef:
        key: IMMICH.AUTHENTIK_CLIENT_ID
      secretKey: IMMICH_CLIENT_ID
    - remoteRef:
        key: IMMICH.AUTHENTIK_CLIENT_SECRET
      secretKey: IMMICH_CLIENT_SECRET
    - remoteRef:
        key: JUPYTERHUB.AUTHENTIK_CLIENT_ID
      secretKey: JUPYTERHUB_CLIENT_ID
    - remoteRef:
        key: JUPYTERHUB.AUTHENTIK_CLIENT_SECRET
      secretKey: JUPYTERHUB_CLIENT_SECRET
    - remoteRef:
        key: OPENWEBUI.AUTHENTIK_CLIENT_ID
      secretKey: OPENWEBUI_CLIENT_ID
    - remoteRef:
        key: OPENWEBUI.AUTHENTIK_CLIENT_SECRET
      secretKey: OPENWEBUI_CLIENT_SECRET
    - remoteRef:
        key: OWNCLOUD.AUTHENTIK_CLIENT_ID
      secretKey: OWNCLOUD_CLIENT_ID
    - remoteRef:
        key: OWNCLOUD.AUTHENTIK_CLIENT_SECRET
      secretKey: OWNCLOUD_CLIENT_SECRET