apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-external-secret
  namespace: authentik
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: AUTHENTIK_SECRET_KEY
      secretKey: AUTHENTIK_SECRET_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: AUTHENTIK_NOTIFICATIONS_SLACK_WEBHOOK
      secretKey: AUTHENTIK_NOTIFICATIONS_SLACK_WEBHOOK

    # USERS
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: AUTHENTIK_ADMIN_EMAIL
      secretKey: AUTHENTIK_ADMIN_EMAIL
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: AUTHENTIK_ADMIN_PASSWORD
      secretKey: AUTHENTIK_ADMIN_PASSWORD
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: AUTHENTIK_BACKUP_ADMIN_EMAIL
      secretKey: AUTHENTIK_BACKUP_ADMIN_EMAIL
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: AUTHENTIK_BACKUP_ADMIN_PASSWORD
      secretKey: AUTHENTIK_BACKUP_ADMIN_PASSWORD

    # APPLICATIONS
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: ARGOCD_CLIENT_ID
      secretKey: ARGOCD_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: ARGOCD_CLIENT_SECRET
      secretKey: ARGOCD_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: ARGOWF_CLIENT_ID
      secretKey: ARGOWF_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: ARGOWF_CLIENT_SECRET
      secretKey: ARGOWF_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: GRAFANA_CLIENT_ID
      secretKey: GRAFANA_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: GRAFANA_CLIENT_SECRET
      secretKey: GRAFANA_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: HARBOR_CLIENT_ID
      secretKey: HARBOR_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: HARBOR_CLIENT_SECRET
      secretKey: HARBOR_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: IMMICH_CLIENT_ID
      secretKey: IMMICH_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: IMMICH_CLIENT_SECRET
      secretKey: IMMICH_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: JUPYTERHUB_CLIENT_ID
      secretKey: JUPYTERHUB_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: JUPYTERHUB_CLIENT_SECRET
      secretKey: JUPYTERHUB_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: OWNCLOUD_CLIENT_ID
      secretKey: OWNCLOUD_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: OWNCLOUD_CLIENT_SECRET
      secretKey: OWNCLOUD_CLIENT_SECRET
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: authentik-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd