server:
  ingress:
    enabled: false
    hosts:
      - auth.jcan.dev
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prd
postgresql:
  enabled: true
redis:
  enabled: true

# Reference the secret created above
global:
  envFrom:
    - secretRef:
        name: authentik-external-secret
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: authentik-postgresql

blueprints:
  # -- List of config maps to mount blueprints from.
  # Only keys in the configMap ending with `.yaml` will be discovered and applied.
  configMaps:
    - authentik-blueprints