server:
  ingress:
    enabled: false
    hosts:
      - host: authentik.example.com
        paths:
          - path: /
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
postgresql:
  enabled: true
redis:
  enabled: true

# Reference the secret created above
global:
  envFrom:
    - secretRef:
        name: authentik-external-secret
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: authentik-postgresql
