---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vllm-external-secret
  namespace: vllm
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: vllm-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: HUGGING_FACE_HUB_TOKEN
      remoteRef:
        key: HUGGINGFACE.ACCESS_TOKEN
