apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argo-cd
  name: github-runner
  labels:
    app.kubernetes.io/instance: ci
    app.kubernetes.io/part-of: workloads
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/tracking-id: workloads-ci:argoproj.io/Application:argo-cd/github-runner
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - name: gha-runner-scale-set
          wave: 40
        - name: gha-runner-scale-set-controller
          wave: 40
  template:
    metadata:
      name: '{{ .name }}'
      namespace: 'github-runner'
      annotations:
        argocd.argoproj.io/tracking-id: workloads-ci:argoproj.io/Application:argo-cd/{{ .name }}
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
      labels:
        app.kubernetes.io/instance: '{{ .name }}'
        app.kubernetes.io/component: 'github-runner'
        app.kubernetes.io/part-of: workloads-ci
    spec:
      project: workloads-ci
      source:
        repoURL: https://github.com/Kube-Mind/fleet-infra.git
        targetRevision: migration
        path: 'src/workloads/ci/github-runner/{{ .name }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: 'github-runner'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true