apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-runner-external-secret
  namespace: github-runner
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ci/github-runner
        metadataPolicy: None
        property: github_token
      secretKey: github_token
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-runner-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd