apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: gha-runner-scale-set
  namespace: github-runner
  repo: ghcr.io/actions/actions-runner-controller-charts
  valuesFile: values.yaml
  version: 0.12.1
- name: gha-runner-scale-set-controller
  namespace: github-runner
  repo: ghcr.io/actions/actions-runner-controller-charts
  valuesFile: values.yaml
  version: 0.12.1