apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprints
    files:
      - groups.yaml
      - ./apps/argo-cd.yaml