apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprints
    files:
      - flows-default-provider-authorization-one-time-consent.yaml
      - groups.yaml
      - oauth-scopes.yaml
      - ./apps/argo-cd.yaml