apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml

helmCharts:
- name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
  releaseName: nfs-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  valuesFile: values.yaml
  version: 4.0.18
  includeCRDs: true