---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argowf-external-secret
  namespace: argo-workflows
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: argowf-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: ARGOWF_CLIENT_ID
      remoteRef:
        key: ARGOWF.AUTHENTIK_CLIENT_ID
    - secretKey: ARGOWF_CLIENT_SECRET
      remoteRef:
        key: ARGOWF.AUTHENTIK_CLIENT_SECRET
    - secretKey: config.json
      remoteRef:
        key: HARBOR.REGCRED