apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argowf-external-secret
  namespace: argo-workflows
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/storage/harbor
        metadataPolicy: None
        property: regcred
      secretKey: config.json
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: ARGOWF_CLIENT_ID
      secretKey: ARGOWF_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: ARGOWF_CLIENT_SECRET
      secretKey: ARGOWF_CLIENT_SECRET
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: argowf-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd