---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: harbor-buffering
  namespace: harbor
spec:
  buffering:
    maxRequestBodyBytes: 0              # 0 = unlimited (or set > image size)
    memRequestBodyBytes: 10485760       # 10MB in memory, rest in temp file
    maxResponseBodyBytes: 0             # unlimited response size
    memResponseBodyBytes: 10485760
    retryExpression: "IsNetworkError()" # only retry for network-level issues
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ocr.jcan.dev`)
      kind: Rule
      services:
        - name: harbor-core
          port: 80
          serversTransport: harbor-transport
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: harbor-transport
  namespace: harbor
spec:
  insecureSkipVerify: true  # Set to true if Harbor uses self-signed TLS certs
  forwardingTimeouts:
    dialTimeout: 600s
    idleConnTimeout: 360s
    pingTimeout: 120s
    readIdleTimeout: 180s
    responseHeaderTimeout: 360s