apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml

helmCharts:
- name: ollama
  namespace: ollama
  releaseName: ollama
  repo: https://otwld.github.io/ollama-helm/
  valuesFile: values.yaml
  version: 1.25.0