apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kaniko
  namespace: argo-workflows
spec:
  arguments:
    parameters:
      - name: repo
        value: https://github.com/argoproj/argo-workflows
      - name: branch
        value: main
      - name: dockerfile
        value: test/e2e/images/argosay/v2/Dockerfile
      - name: image
        value: ocr.jcan.dev/library/argosay:0.0.1
      - name: context
        value: test/e2e/images/argosay/v2
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: build
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 32Gi
  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            template: clone
            arguments:
              parameters:
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
          - name: image
            template: image
            arguments:
              parameters:
                - name: dockerfile
                  value: "{{workflow.parameters.dockerfile}}"
                - name: image
                  value: "{{workflow.parameters.image}}"
                - name: context
                  value: "{{workflow.parameters.context}}"
            depends: "clone"

    - name: clone
      inputs:
        parameters:
          - name: repo
          - name: branch
      container:
        image: alpine/git:v2.26.2
        workingDir: /work
        volumeMounts:
          - name: work
            mountPath: /work
        args:
          - clone
          - --recursive
          - --branch
          - "{{inputs.parameters.branch}}"
          - --single-branch
          - "{{inputs.parameters.repo}}"
          - app

    - name: image
      inputs:
        parameters:
          - name: dockerfile
          - name: image
          - name: context
      volumes:
        - name: docker-config
          secret:
            secretName: argowf-external-secret
      container:
        image: gcr.io/kaniko-project/executor:v1.23.2
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "8Gi"
            cpu: "8"
        workingDir: /work/app/
        volumeMounts:
          - name: work
            mountPath: /work
          - name: build
            mountPath: /kaniko/stages
          - name: docker-config
            mountPath: /kaniko/.docker
        args:
          - --dockerfile={{inputs.parameters.dockerfile}}/Dockerfile
          - --context=/work/app/{{inputs.parameters.context}}
          - --destination={{inputs.parameters.image}}
          - --no-push-cache