---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-env
  namespace: immich
data:
  UPLOAD_LOCATION: "/data"
  DB_DATABASE_NAME: "immichdb"
  DB_USERNAME: "immichuser"
  DB_HOSTNAME: "immich-postgres.immich.svc.cluster.local"
  REDIS_HOSTNAME: "immich-redis.immich.svc.cluster.local"