apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-external-secret
  namespace: immich
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: media/management/immich
        metadataPolicy: None
        property: IMMICH_DB_PASSWORD
      secretKey: IMMICH_DB_PASSWORD
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: IMMICH_CLIENT_ID
      secretKey: IMMICH_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: IMMICH_CLIENT_SECRET
      secretKey: IMMICH_CLIENT_SECRET
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: immich-external-secret
    template:
        engineVersion: v2
        metadata:
          labels:
            app.kubernetes.io/part-of: argocd
        data:
          DB_PASSWORD: "{{ .IMMICH_DB_PASSWORD }}"
          immich-config.yaml: |
                ffmpeg:
                  accel: disabled
                  accelDecode: false
                  acceptedAudioCodecs:
                  - aac
                  - mp3
                  - libopus
                  - pcm_s16le
                  acceptedContainers:
                  - mov
                  - ogg
                  - webm
                  acceptedVideoCodecs:
                  - h264
                  bframes: -1
                  cqMode: auto
                  crf: 23
                  gopSize: 0
                  maxBitrate: "0"
                  preferredHwDevice: auto
                  preset: ultrafast
                  refs: 0
                  targetAudioCodec: aac
                  targetResolution: "720"
                  targetVideoCodec: h264
                  temporalAQ: false
                  threads: 0
                  tonemap: hable
                  transcode: required
                  twoPass: false
                image:
                  colorspace: p3
                  extractEmbedded: false
                  preview:
                    format: jpeg
                    quality: 80
                    size: 1440
                  thumbnail:
                    format: webp
                    quality: 80
                    size: 250
                job:
                  backgroundTask:
                    concurrency: 5
                  faceDetection:
                    concurrency: 2
                  library:
                    concurrency: 5
                  metadataExtraction:
                    concurrency: 5
                  migration:
                    concurrency: 5
                  notifications:
                    concurrency: 5
                  search:
                    concurrency: 5
                  sidecar:
                    concurrency: 5
                  smartSearch:
                    concurrency: 2
                  thumbnailGeneration:
                    concurrency: 3
                  videoConversion:
                    concurrency: 1
                library:
                  scan:
                    cronExpression: 0 0 * * *
                    enabled: true
                  watch:
                    enabled: false
                logging:
                  enabled: true
                  level: log
                server:
                  externalDomain: https://immich.jcan.dev
                machineLearning:
                  clip:
                    enabled: true
                    modelName: ViT-B-32__openai
                  duplicateDetection:
                    enabled: true
                    maxDistance: 0.01
                  enabled: true
                  facialRecognition:
                    enabled: true
                    maxDistance: 0.5
                    minFaces: 1
                    minScore: 0.7
                    modelName: buffalo_l
                  urls:
                    - http://immich-machine-learning:3003
                map:
                  darkStyle: https://tiles.immich.cloud/v1/style/dark.json
                  enabled: true
                  lightStyle: https://tiles.immich.cloud/v1/style/light.json
                metadata:
                  faces:
                    import: true
                newVersionCheck:
                  enabled: true
                oauth:
                  enabled: true
                  issuerUrl: "https://auth.jcan.dev/application/o/immich/"
                  scope: "openid email profile"
                  autoLaunch: true
                  autoRegister: true
                  buttonText: "Login with SSO"
                  clientId: "{{ .IMMICH_CLIENT_ID }}"
                  clientSecret: "{{ .IMMICH_CLIENT_SECRET }}"
                passwordLogin:
                  enabled: false
                reverseGeocoding:
                  enabled: true
                theme:
                  customCss: ""
                trash:
                  days: 30
                  enabled: true
                backup:
                  database:
                    enabled: true
                    cronExpression: "0 02 * * *"
                    keepLastAmount: 14
                notifications:
                  smtp:
                    enabled: false
                    from: ""
                    replyTo: ""
                    transport:
                      ignoreCert: false
                      host: ""
                      port: 587
                      username: ""
                      password: ""
                user:
                  deleteDelay: 7
      