apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml

helmCharts:
- name: kafka
  namespace: kafka
  releaseName: kafka
  repo: https://charts.bitnami.com/bitnami
  valuesFile: values.yaml
  version: 32.3.10