apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-external-secret
  namespace: argo-cd
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/core/argo-cd
        metadataPolicy: None
        property: slack-token
      secretKey: slack-token
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/core/argo-cd
        metadataPolicy: None
        property: GITLAB_APPLICATION_ID
      secretKey: GITLAB_APPLICATION_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/core/argo-cd
        metadataPolicy: None
        property: GITLAB_CLIENT_SECRET
      secretKey: GITLAB_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: ARGOCD_CLIENT_ID
      secretKey: ARGOCD_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: ARGOCD_CLIENT_SECRET
      secretKey: ARGOCD_CLIENT_SECRET
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: argocd-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd