# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: argocd-external-secret
#   namespace: argo-cd
# spec:
#   data:
#     - remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         key: platform/core/argo-cd
#         metadataPolicy: None
#         nullBytePolicy: Ignore
#         property: slack-token
#       secretKey: slack-token
#     - remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         key: platform/core/argo-cd
#         metadataPolicy: None
#         nullBytePolicy: Ignore
#         property: GITLAB_APPLICATION_ID
#       secretKey: GITLAB_APPLICATION_ID
#     - remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         key: platform/core/argo-cd
#         metadataPolicy: None
#         nullBytePolicy: Ignore
#         property: GITLAB_CLIENT_SECRET
#       secretKey: GITLAB_CLIENT_SECRET
#     - remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         key: platform/security/authentik
#         metadataPolicy: None
#         nullBytePolicy: Ignore
#         property: ARGOCD_CLIENT_ID
#       secretKey: ARGOCD_CLIENT_ID
#     - remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         key: platform/security/authentik
#         metadataPolicy: None
#         nullBytePolicy: Ignore
#         property: ARGOCD_CLIENT_SECRET
#       secretKey: ARGOCD_CLIENT_SECRET
#   refreshInterval: 15s
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: vault
#   target:
#     creationPolicy: Owner
#     deletionPolicy: Retain
#     name: argocd-external-secret
#     template:
#       engineVersion: v2
#       mergePolicy: Replace
#       metadata:
#         labels:
#           app.kubernetes.io/part-of: argocd
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-external-secret
  namespace: argo-cd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsstore
    kind: ClusterSecretStore
  target:
    name: argocd-external-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: slack-token
      remoteRef:
        key: SLACK_TOKEN
    - secretKey: GITLAB_APPLICATION_ID
      remoteRef:
        key: ARGOCD.GITLAB_APPLICATION_ID
    - secretKey: GITLAB_CLIENT_SECRET
      remoteRef:
        key: ARGOCD.GITLAB_CLIENT_SECRET
    - secretKey: ARGOCD_CLIENT_ID
      remoteRef:
        key: ARGOCD.AUTHENTIK_CLIENT_ID
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: ARGOCD.AUTHENTIK_CLIENT_SECRET