preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  taintToleration:
    toleratorions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/etcd
        operator: Exists
        effect: NoExecute

longhornManager:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/etcd
      operator: Exists
      effect: NoExecute

service:
  ui:
    type: NodePort
    nodePort: 31412

defaultBackupStore:
  backupTarget: 'nfs://192.168.1.192:/volume4/snapshots/longhorn'
  pollInterval: 180

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  reclaimPolicy: Retain
  defaultFsType: ext4
  snapshotMaxCount: 60
  defaultDataLocality: best-effort

longhornDriver:
  priorityClass: system-cluster-critical