apiVersion: apps/v1
kind: Deployment
metadata:
  name: ska-pst-dspsr-builder
  labels:
    app: ska-pst-dspsr-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ska-pst-dspsr-builder
  template:
    metadata:
      labels:
        app: ska-pst-dspsr-builder
    spec:
      hostNetwork: false
      runtimeClassName: nvidia
      containers:
        - name: dspsr
          securityContext:
            privileged: false
          image: "registry.gitlab.com/ska-telescope/pst/ska-pst-dsp-tools/ska-pst-dspsr-builder:0.0.12"
          imagePullPolicy: IfNotPresent
          command:
            - bash
          workingDir: /mnt/dspsr
          tty: true
          envFrom: []
          ports: []
          resources:
            limits:
              cpu: 4000m
              memory: 8000Mi
            requests:
              cpu: 4000m
              memory: 4000Mi
          volumeMounts:
          # NFS mount
            - name: ska-pst-dspsr-builder
              mountPath: /mnt/dspsr
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - baldr
      tolerations:
        - effect: NoExecute
          key: nvidia.com/gpu
          value: "true"
        - effect: NoSchedule
          key: skao.int/dedicated
          value: pst
      volumes:
        # ska-pst-core storage
          - name: ska-pst-dspsr-builder
            persistentVolumeClaim:
              claimName: ska-pst-dspsr-builder