apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-security
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/tracking-id: platform:argoproj.io/Application:argo-cd/security
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: security
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argo-cd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: authentik
            wave: 20
            ignoreDifferences:
              - group: ''
                kind: Secret
                name: authentik-postgresql
                jsonPointers:
                  - /data/password
                  - /data/postgres-password
              - group: ''
                kind: PersistentVolumeClaim
                jqPathExpressions:
                - '.metadata.creationTimestamp'

          - name: openbao
            wave: 10
            ignoreDifferences:
              - group: admissionregistration.k8s.io
                kind: MutatingWebhookConfiguration
                jsonPointers:
                  - /webhooks/0/clientConfig/caBundle
              - group: apps
                kind: StatefulSet
                jqPathExpressions:
                - '.spec.volumeClaimTemplates[].apiVersion'
                - '.spec.volumeClaimTemplates[].kind'
              - group: ''
                kind: PersistentVolumeClaim
                jqPathExpressions:
                - '.metadata.creationTimestamp'

          - name: secrets-integrator
            wave: 20
  template:
    metadata:
      name: '{{ .name }}'
      annotations:
        argocd.argoproj.io/tracking-id: platform-security:argoproj.io/Application:argo-cd/{{ .name }}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/instance: '{{ .name }}'
        app.kubernetes.io/component: '{{ .name }}'
        app.kubernetes.io/part-of: platform-security
    spec:
      project: platform-security
      source:
        repoURL: https://github.com/Kube-Mind/fleet-infra.git
        targetRevision: HEAD
        path: 'src/platform/security/{{ .name }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: '{{ .name }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
  templatePatch: |
    {{- if .ignoreDifferences }}
    spec:
      ignoreDifferences:
      {{- toYaml .ignoreDifferences | nindent 12 }}
    {{- end }}