apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-security
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/tracking-id: platform:argoproj.io/Application:argo-cd/platform-security
  labels:
    app.kubernetes.io/instance: 'platform-security'
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argo-cd
spec:
  description: Project for security platform applications
  sourceRepos:
    - 'https://github.com/Kube-Mind/fleet-infra.git'
  destinations:
    - namespace: 'authentik'
      server: '*'
    - namespace: 'argo-cd'
      server: '*'
    - namespace: 'argo-workflows'
      server: '*'
    - namespace: 'dnsfix'
      server: '*'
    - namespace: 'github-runner'
      server: '*'
    - namespace: 'gitlab-runner'
      server: '*'
    - namespace: 'harbor'
      server: '*'
    - namespace: 'jupyterhub'
      server: '*'
    - namespace: 'kube-prometheus-stack'
      server: '*'
    - namespace: 'openbao'
      server: '*'
    - namespace: 'open-webui'
      server: '*'
    - namespace: 'pft'
      server: '*'
    - namespace: 'rabbitmq'
      server: '*'
    - namespace: 'secrets-integrator'
      server: '*'
    - namespace: 'stable-diffusion-webui'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'