apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-security
  namespace: argo-cd
  labels:
    app.kubernetes.io/instance: 'infra-security'
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/tracking-id: infrastructure:argoproj.io/Application:argo-cd/infra-security
spec:
  description: Project for security infrastructure applications
  sourceRepos:
    - 'https://gitlab.com/Kube-Mind/fleet-infra.git'
  destinations:
    - namespace: 'openbao'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'