k8sServiceHost: localhost
k8sServicePort: 6444
# --- CRITICAL SAFETY SETTINGS ---
# Enable eBPF-based Service load balancing
kubeProxyReplacement: true 

# 4. BPF Settings: Refine for stability
bpf:
  hostRouting: true

# Allow Cilium to manage CNI configuration natively
cni:
  exclusive: true

# MTU (9000 jumbo - 50 vxlan overhead)
MTU: 8950

operator:
  rollOutPods: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true
agent: true
agentConfig:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      value: "true"
      effect: NoSchedule
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi

#debug:
#  enabled: true

k8sClientRateLimit:
  qps: 20
  burst: 100

gatewayAPI:
  enabled: false
envoy:
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy: [NET_ADMIN, PERFMON, BPF]
  streamIdleTimeoutDurationSeconds: 0
  idleTimeoutDurationSeconds: 60
  connectTimeoutSeconds: 2
  maxConnectionDurationSeconds: 0

hubble:
  peerService:
    clusterDomain: cluster.local
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  ui:
    enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

l2announcements:
  enabled: true

externalIPs:
  enabled: true

ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true
  service:
    type: LoadBalancer
    insecureNodePort: 30080
    secureNodePort: 30443

# Network Policy Audit Mode - Log violations without blocking
policyAuditMode: false

# mTLS
authentication:
  enabled: false
