apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-external-secret
  namespace: gitlab-runner
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ci/gitlab-runner
        metadataPolicy: None
        property: runner-registration-token
      secretKey: runner-registration-token
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: workloads/ci/gitlab-runner
        metadataPolicy: None
        property: runner-token
      secretKey: runner-token
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gitlab-runner-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd