{{- $appNamespace := "argo-cd" -}}
{{- range $app, $_ := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $app }}
  namespace: {{ $appNamespace }}
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
{{- end }}

