apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argo-cd
  name: platform-storage
  labels:
    app.kubernetes.io/instance: storage
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/tracking-id: default:argoproj.io/Application:argo-cd/platform-storage
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - name: longhorn
          wave: 0
        - name: nfs-provisioner
          wave: 10
  template:
    metadata:
      name: '{{ .name }}'
      namespace: '{{ .name }}'
      annotations:
        argocd.argoproj.io/tracking-id: platform-storage:argoproj.io/Application:argo-cd/'{{ .name }}'
      labels:
        app.kubernetes.io/instance: '{{ .name }}'
        app.kubernetes.io/component: '{{ .name }}'
        app.kubernetes.io/part-of: platform-storage
    spec:
      project: platform-storage
      source:
        repoURL: https://github.com/Kube-Mind/fleet-infra.git
        targetRevision: migration
        path: 'src/platform/core/{{ .name }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: '{{ .name }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true