name: Notify Slack on Renovate PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    if: contains(github.event.pull_request.title, 'chore(deps)')
    runs-on:
      group: homelab
      labels: github-scale-set
    container:
      image: ocr.jcan.dev/dh/node:20-alpine
    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_RENOVATE }}
          webhook-type: incoming-webhook
          payload: | 
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: ":package: *<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>*"
              - type: context
                elements:
                  - type: mrkdwn
                    text: "Triggered by `${{ github.actor }}` on *${{ github.event.repository.name }}*"
              - type: divider
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*Branch:*\n`${{ github.head_ref }}`"
                  - type: mrkdwn
                    text: "*PR Number:*\n#${{ github.event.pull_request.number }}"