name: Notify Slack on Renovate PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    if: contains(github.event.pull_request.title, 'chore(deps)')
    runs-on:
      group: homelab
      labels: github-scale-set
    container:
      image: ocr.jcan.dev/dh/curlimages/curl:8.5.0
    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ env.SLACK_WEBHOOK_URL_RENOVATE }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              *<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>*  
              _by `${{ github.actor }}` on `${{ github.event.repository.name }}`_  
              ```  
              ${{ github.event.pull_request.body }}  
              ```
