name: Notify Slack on Renovate PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    if: contains(github.event.pull_request.title, 'update helm and oci chart versions')
    runs-on:
      group: homelab
      labels: github-scale-set
    container:
      image: ocr.jcan.dev/dh/curlimages/curl:8.5.0
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL_RENOVATE: ${{ secrets.SLACK_WEBHOOK_URL_RENOVATE }}
          BODY: ${{ github.event.pull_request.body }}
        run: |
          SANITIZED_BODY=$(printf '%s' "$BODY" | sed 's/"/\\"/g; s/$/\\n/' | tr -d '\n')
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$SANITIZED_BODY\"}" \
            "$SLACK_WEBHOOK_URL_RENOVATE"
