name: Notify Slack on Renovate PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    if: contains(github.event.pull_request.title, 'update helm and oci chart versions')
    runs-on:
      group: homelab
      labels: github-scale-set
    container:
      image: ocr.jcan.dev/dh/curlimages/curl:8.5.0
    env:
      BODY64: ${{ github.event.pull_request.body }}
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL_RENOVATE: ${{ secrets.SLACK_WEBHOOK_URL_RENOVATE }}
        run: |
          # Encode and decode body within the same step
          ENCODED_BODY=$(echo "$BODY64" | base64 -w 0)
          DECODED_BODY=$(echo "$ENCODED_BODY" | base64 -d | sed ':a;N;$!ba;s/"/\\"/g; s/\n/\\n/g')

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$DECODED_BODY\"}" \
            "$SLACK_WEBHOOK_URL_RENOVATE"
