name: Notify Slack on Renovate PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    if: contains(github.event.pull_request.title, 'chore(deps)')
    runs-on:
      group: homelab
      labels: github-scale-set
    container:
      image: ocr.jcan.dev/dh/curlimages/curl:8.5.0
    steps:
      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
        with:
          channel-id: 'C07HRJFATEV'
          # For posting a simple plain text message
          slack-message: |
            *<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>*  
            _by `${{ github.actor }}` on `${{ github.event.repository.name }}`_ 
            ```
            ${{ github.event.pull_request.body }}
            ```
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_RENOVATE }}
