name: Notify Slack on Renovate PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    if: contains(github.event.pull_request.title, 'update helm and oci chart versions')
    runs-on:
      group: homelab
      labels: github-scale-set
    container:
      image: ocr.jcan.dev/dh/curlimages/curl:8.5.0
    steps:
      - name: Get PR body
        id: get-body
        run: |
          echo "body64=$(echo "${{ github.event.pull_request.body }}" | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL_RENOVATE: ${{ secrets.SLACK_WEBHOOK_URL_RENOVATE }}
        run: |
          # Decode the body from the previous step
          DECODED_BODY=$(echo "${{ steps.get-body.outputs.body64 }}" | base64 --decode)

          # Optional: wrap as proper JSON string to handle quotes/newlines
          MESSAGE=$(echo "$DECODED_BODY" | jq -Rs .)

          # Send Slack notification
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": $MESSAGE }" \
            "$SLACK_WEBHOOK_URL_RENOVATE"
