spec:
  project: monitoring-stack

apps:
  dnsfix:
    automated: false
    installType: remoteHelm
    repoURL: https://gitlab.com/kube-mind/apps/dnsfix.git
    path: charts/dnsfix
    targetRevision: HEAD

  chartwatch:
    automated: false
    installType: remoteHelm
    repoURL: https://gitlab.com/kube-mind/apps/chartwatch.git
    path: charts/chartwatch
    targetRevision: HEAD

  kube-prometheus-stack:
    automated: false
    chartName: kube-prometheus-stack
    extraLabels:
      web-gui: "true"
    extraSyncOptions:
      - ServerSideApply=true
    installType: helm
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jqPathExpressions:
          - .spec.template.metadata.annotations."checksum/secret"
      - kind: Secret
        jsonPointers:
          - /data/admin-password
          - /data/ldap-toml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.8.0
