spec:
  project: infra-management

apps:
  argo-cd:
    automated: true
    chartName: argo-cd
    extraLabels:
      web-gui: "true"
    installType: helm
    repoURL: https://argoproj.github.io/argo-helm
    syncWave: "0.1"
    targetRevision: 8.0.12

  cert-manager:
    automated: true
    chartName: cert-manager
    installType: helm
    repoURL: https://charts.jetstack.io
    syncWave: "0.2"
    targetRevision: v1.17.2

  external-secrets:
    automated: true
    chartName: external-secrets
    installType: helm
    repoURL: https://charts.external-secrets.io
    syncWave: "0.2"
    targetRevision: 0.17.0

  k3s-upgrader:
    automated: true
    installType: localKustomize
    syncWave: "0.2"

  longhorn:
    automated: true
    chartName: longhorn
    ignoreDifferences:
      - group: ''
        kind: CustomResourceDefinition
        jqPathExpressions:
          - .spec.preserveUnknownFields
    repoURL: https://charts.longhorn.io
    installType: helm
    syncWave: "0.2"
    targetRevision: 1.9.0

  nfs-provisioner:
    automated: true
    chartName: nfs-subdir-external-provisioner
    extraLabels:
      web-gui: "true"
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    installType: helm
    syncWave: "0.2"
    targetRevision: 4.0.18

  nvidia-operator:
    automated: true
    chartName: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    installType: helm
    syncWave: "0.2"
    targetRevision: v25.3.0

  openbao:
    automated: true
    chartName: openbao
    extraLabels:
      web-gui: "true"
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
    repoURL: https://openbao.github.io/openbao-helm
    installType: helm
    syncWave: "0.3"
    targetRevision: 0.12.0
