spec:
  project: infra-monitoring

apps:
  kube-prometheus-stack:
    automated: false
    chartName: kube-prometheus-stack
    extraLabels:
      web-gui: "true"
    extraSyncOptions:
      - ServerSideApply=true
    installType: helm
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jqPathExpressions:
          - .spec.template.metadata.annotations."checksum/secret"
      - kind: Secret
        jsonPointers:
          - /data/admin-password
          - /data/ldap-toml
    repoURL: https://prometheus-community.github.io/helm-charts
    syncWave: "2.1"
    targetRevision: 74.0.0
  
  neuvector:
    automated: false
    chartName: core
    extraLabels:
      web-gui: "true"
    installType: helm
    repoURL: https://neuvector.github.io/neuvector-helm/
    syncWave: "2.1"
    targetRevision: 2.8.6
