spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Kube-Mind/fleet-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true

apps: {}