---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-uploads-pvc
  namespace: immich
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 500Gi
  volumeName: pvc-c43525e7-d949-4d5a-8328-3b35bd55e707